#pragma once

/**
 * @file
 * Figure types.
 */

#include <string_view>

/**
 * Figure types
 */
typedef enum {
    FIGURE_NONE = 0,
    FIGURE_IMMIGRANT = 1,
    FIGURE_EMIGRANT = 2,
    FIGURE_HOMELESS = 3,
    FIGURE_CART_PUSHER = 4,
    FIGURE_LABOR_SEEKER = 5,
    FIGURE_EXPLOSION = 6,
    FIGURE_TAX_COLLECTOR = 7,
    FIGURE_ENGINEER = 8,
    FIGURE_WAREHOUSEMAN = 9,
    FIGURE_PREFECT = 10,
    FIGURE_FORT_JAVELIN = 11,
    FIGURE_FORT_MOUNTED = 12,
    FIGURE_FORT_LEGIONARY = 13,
    FIGURE_FORT_STANDARD = 14,
    FIGURE_ACTOR = 15,
    FIGURE_GLADIATOR = 16,
    FIGURE_LION_TAMER = 17,
    FIGURE_CHARIOTEER = 18,
    FIGURE_TRADE_CARAVAN = 19,
    FIGURE_TRADE_SHIP = 20,
    FIGURE_TRADE_CARAVAN_DONKEY = 21,
    FIGURE_PROTESTER = 22,
    FIGURE_CRIMINAL = 23,
    FIGURE_RIOTER = 24,
    FIGURE_FISHING_BOAT = 25,
    FIGURE_MARKET_TRADER = 26,
    FIGURE_PRIEST = 27,
    FIGURE_SCHOOL_CHILD = 28,
    FIGURE_TEACHER = 29,
    FIGURE_LIBRARIAN = 30,
    FIGURE_BARBER = 31,
    FIGURE_BATHHOUSE_WORKER = 32,
    FIGURE_DOCTOR = 33,
    FIGURE_SURGEON = 34,
    FIGURE_WORKER = 35,
    FIGURE_MAP_FLAG = 36,
    FIGURE_FLOTSAM = 37,
    FIGURE_DOCKER = 38,
    FIGURE_MARKET_SUPPLIER = 39,
    FIGURE_PATRICIAN = 40,
    FIGURE_INDIGENOUS_NATIVE = 41,
    FIGURE_TOWER_SENTRY = 42,
    FIGURE_ENEMY43_SPEAR = 43,
    FIGURE_ENEMY44_SWORD = 44,
    FIGURE_ENEMY45_SWORD = 45,
    FIGURE_ENEMY46_CAMEL = 46,
    FIGURE_ENEMY47_ELEPHANT = 47,
    FIGURE_ENEMY48_CHARIOT = 48,
    FIGURE_ENEMY49_FAST_SWORD = 49,
    FIGURE_ENEMY50_SWORD = 50,
    FIGURE_ENEMY51_SPEAR = 51,
    FIGURE_ENEMY52_MOUNTED_ARCHER = 52,
    FIGURE_ENEMY53_AXE = 53,
    FIGURE_ENEMY54_GLADIATOR = 54,
    FIGURE_ENEMY_CAESAR_JAVELIN = 55,
    FIGURE_ENEMY_CAESAR_MOUNTED = 56,
    FIGURE_ENEMY_CAESAR_LEGIONARY = 57,
    FIGURE_NATIVE_TRADER = 58,
    FIGURE_ARROW = 59,
    FIGURE_JAVELIN = 60,
    FIGURE_BOLT = 61,
    FIGURE_BALLISTA = 62,
    FIGURE_CREATURE = 63,
    FIGURE_MISSIONARY = 64,
    FIGURE_FISH_GULLS = 65,
    FIGURE_DELIVERY_BOY = 66,
    FIGURE_SHIPWRECK = 67,
    FIGURE_SHEEP = 68,
    FIGURE_WOLF = 69,
    FIGURE_ZEBRA = 70,
    FIGURE_SPEAR = 71,
    FIGURE_HIPPODROME_HORSES = 72,
    FIGURE_NEW_TYPES = 73,
    FIGURE_WORK_CAMP_WORKER = 73,
    FIGURE_WORK_CAMP_SLAVE = 74,
    FIGURE_WORK_CAMP_ARCHITECT = 75,
    FIGURE_MESS_HALL_SUPPLIER = 76,
    FIGURE_MESS_HALL_COLLECTOR = 77,
    FIGURE_PRIEST_SUPPLIER = 78,
    FIGURE_BARKEEP = 79,
    FIGURE_BARKEEP_SUPPLIER = 80,
    FIGURE_TOURIST = 81,
    FIGURE_WATCHMAN = 82,
    FIGURE_WATCHTOWER_ARCHER = 83,
    FIGURE_FRIENDLY_ARROW = 84,
    FIGURE_CARAVANSERAI_SUPPLIER = 85,
    FIGURE_CRIMINAL_ROBBER = 86,
    FIGURE_CRIMINAL_LOOTER = 87,
    FIGURE_CARAVANSERAI_COLLECTOR = 88,
    FIGURE_LIGHTHOUSE_SUPPLIER = 89,
    FIGURE_MESS_HALL_FORT_SUPPLIER = 90,
    FIGURE_DEPOT_CART_PUSHER = 91,
    FIGURE_FORT_INFANTRY = 92,
    FIGURE_BEGGAR = 93,
    FIGURE_FORT_ARCHER = 94,
    FIGURE_ENEMY_CATAPULT = 95,
    FIGURE_CATAPULT_MISSILE = 96,
    FIGURE_TYPE_MAX = 97
} figure_type;

struct FigureTypeXmlName {
    std::string_view name;
    figure_type type;
};

inline constexpr FigureTypeXmlName FIGURE_TYPE_XML_NAMES[] = {
    { "immigrant", FIGURE_IMMIGRANT },
    { "emigrant", FIGURE_EMIGRANT },
    { "homeless", FIGURE_HOMELESS },
    { "cart_pusher", FIGURE_CART_PUSHER },
    { "labor_seeker", FIGURE_LABOR_SEEKER },
    { "engineer", FIGURE_ENGINEER },
    { "prefect", FIGURE_PREFECT },
    { "warehouseman", FIGURE_WAREHOUSEMAN },
    { "trade_caravan", FIGURE_TRADE_CARAVAN },
    { "trade_caravan_donkey", FIGURE_TRADE_CARAVAN_DONKEY },
    { "priest", FIGURE_PRIEST },
    { "doctor", FIGURE_DOCTOR },
    { "surgeon", FIGURE_SURGEON },
    { "tax_collector", FIGURE_TAX_COLLECTOR },
    { "missionary", FIGURE_MISSIONARY },
    { "patrician", FIGURE_PATRICIAN },
    { "beggar", FIGURE_BEGGAR },
    { "market_trader", FIGURE_MARKET_TRADER },
    { "market_supplier", FIGURE_MARKET_SUPPLIER },
    { "delivery_boy", FIGURE_DELIVERY_BOY },
    { "actor", FIGURE_ACTOR },
    { "gladiator", FIGURE_GLADIATOR },
    { "lion_tamer", FIGURE_LION_TAMER },
    { "indigenous_native", FIGURE_INDIGENOUS_NATIVE },
    { "map_flag", FIGURE_MAP_FLAG },
    { "docker", FIGURE_DOCKER },
    { "trade_ship", FIGURE_TRADE_SHIP },
    { "native_trader", FIGURE_NATIVE_TRADER },
    { "tower_sentry", FIGURE_TOWER_SENTRY },
    { "watchman", FIGURE_WATCHMAN },
    { "watchtower_archer", FIGURE_WATCHTOWER_ARCHER },
    { "enemy43_spear", FIGURE_ENEMY43_SPEAR },
    { "enemy44_sword", FIGURE_ENEMY44_SWORD },
    { "enemy45_sword", FIGURE_ENEMY45_SWORD },
    { "enemy46_camel", FIGURE_ENEMY46_CAMEL },
    { "enemy47_elephant", FIGURE_ENEMY47_ELEPHANT },
    { "enemy48_chariot", FIGURE_ENEMY48_CHARIOT },
    { "enemy49_fast_sword", FIGURE_ENEMY49_FAST_SWORD },
    { "enemy50_sword", FIGURE_ENEMY50_SWORD },
    { "enemy51_spear", FIGURE_ENEMY51_SPEAR },
    { "enemy52_mounted_archer", FIGURE_ENEMY52_MOUNTED_ARCHER },
    { "enemy53_axe", FIGURE_ENEMY53_AXE },
    { "enemy54_gladiator", FIGURE_ENEMY54_GLADIATOR },
    { "enemy_caesar_javelin", FIGURE_ENEMY_CAESAR_JAVELIN },
    { "enemy_caesar_mounted", FIGURE_ENEMY_CAESAR_MOUNTED },
    { "enemy_caesar_legionary", FIGURE_ENEMY_CAESAR_LEGIONARY },
    { "enemy_catapult", FIGURE_ENEMY_CATAPULT },
    { "sheep", FIGURE_SHEEP },
    { "wolf", FIGURE_WOLF },
    { "zebra", FIGURE_ZEBRA },
    { "protester", FIGURE_PROTESTER },
    { "criminal", FIGURE_CRIMINAL },
    { "rioter", FIGURE_RIOTER },
    { "criminal_robber", FIGURE_CRIMINAL_ROBBER },
    { "criminal_looter", FIGURE_CRIMINAL_LOOTER },
    { "charioteer", FIGURE_CHARIOTEER },
    { "teacher", FIGURE_TEACHER },
    { "librarian", FIGURE_LIBRARIAN },
    { "barber", FIGURE_BARBER },
    { "bathhouse_worker", FIGURE_BATHHOUSE_WORKER },
    { "school_child", FIGURE_SCHOOL_CHILD },
    { "tourist", FIGURE_TOURIST },
    { "depot_cart_pusher", FIGURE_DEPOT_CART_PUSHER },
    { "fort_javelin", FIGURE_FORT_JAVELIN },
    { "javelin_soldier", FIGURE_FORT_JAVELIN },
    { "fort_mounted", FIGURE_FORT_MOUNTED },
    { "mounted_soldier", FIGURE_FORT_MOUNTED },
    { "fort_legionary", FIGURE_FORT_LEGIONARY },
    { "legionary", FIGURE_FORT_LEGIONARY },
    { "fort_infantry", FIGURE_FORT_INFANTRY },
    { "infantry_soldier", FIGURE_FORT_INFANTRY },
    { "fort_archer", FIGURE_FORT_ARCHER },
    { "archer_soldier", FIGURE_FORT_ARCHER },
    { "fort_standard", FIGURE_FORT_STANDARD },
    { "hippodrome_horses", FIGURE_HIPPODROME_HORSES },
    { "work_camp_worker", FIGURE_WORK_CAMP_WORKER },
    { "work_camp_slave", FIGURE_WORK_CAMP_SLAVE },
    { "work_camp_architect", FIGURE_WORK_CAMP_ARCHITECT },
    { "mess_hall_supplier", FIGURE_MESS_HALL_SUPPLIER },
    { "ballista", FIGURE_BALLISTA },
    { "mess_hall_collector", FIGURE_MESS_HALL_COLLECTOR },
    { "barkeep", FIGURE_BARKEEP },
    { "barkeep_supplier", FIGURE_BARKEEP_SUPPLIER },
    { "caravanserai_supplier", FIGURE_CARAVANSERAI_SUPPLIER },
    { "lighthouse_supplier", FIGURE_LIGHTHOUSE_SUPPLIER },
    { "caravanserai_collector", FIGURE_CARAVANSERAI_COLLECTOR },
    { "mess_hall_fort_supplier", FIGURE_MESS_HALL_FORT_SUPPLIER },
    { "fishing_boat", FIGURE_FISHING_BOAT },
    { "fish_gulls", FIGURE_FISH_GULLS },
    { "flotsam", FIGURE_FLOTSAM }
};

inline figure_type figure_type_from_xml_name(const char *name)
{
    if (!name) {
        return FIGURE_NONE;
    }
    for (const FigureTypeXmlName &entry : FIGURE_TYPE_XML_NAMES) {
        if (std::string_view(name) == entry.name) {
            return entry.type;
        }
    }
    return FIGURE_NONE;
}

typedef enum {
    ENEMY_UNDEFINED = -1,
    ENEMY_0_BARBARIAN = 0,
    ENEMY_1_NUMIDIAN = 1,
    ENEMY_2_GAUL = 2,
    ENEMY_3_CELT = 3,
    ENEMY_4_GOTH = 4,
    ENEMY_5_PERGAMUM = 5,
    ENEMY_6_SELEUCID = 6,
    ENEMY_7_ETRUSCAN = 7,
    ENEMY_8_GREEK = 8,
    ENEMY_9_EGYPTIAN = 9,
    ENEMY_10_CARTHAGINIAN = 10,
    ENEMY_11_CAESAR = 11,
    ENEMY_MAX
} enemy_type_t;

typedef enum {
    ENEMY_CLASS_ALL = 0,
    ENEMY_CLASS_MELEE = 1,
    ENEMY_CLASS_RANGED = 2,
    ENEMY_CLASS_MOUNTED = 3,
} enemy_class_t;

enum {
    FIGURE_STATE_ALIVE = 1,
    FIGURE_STATE_DEAD = 2
};

enum {
    TERRAIN_USAGE_ANY = 0,
    TERRAIN_USAGE_ROADS = 1,
    TERRAIN_USAGE_ENEMY = 2,
    TERRAIN_USAGE_PREFER_ROADS = 3,
    TERRAIN_USAGE_WALLS = 4,
    TERRAIN_USAGE_ANIMAL = 5,
    TERRAIN_USAGE_ROADS_HIGHWAY = 6,
    TERRAIN_USAGE_PREFER_ROADS_HIGHWAY = 7,
};
