#pragma once
#include "core/config.h"
#include <array>

// Canonical keys and defaults shared by the INI reader and native settings UI.
// Internal state and settings already owned by mods are not exposed here.
struct ConfigOption {
    config_key id;
    const char *key, *name, *category;
    int fallback, minimum, maximum, step;
    bool visible;
};
inline constexpr ConfigOption config_options[] = {
    {CONFIG_GENERAL_ENABLE_AUDIO, "enable_audio", "Enable audio", "General Settings / Audio Options", 1, 0, 1, 1, true},
    {CONFIG_GENERAL_MASTER_VOLUME, "master_volume", "Master volume (%)", "General Settings / Audio Options", 100, 0, 100, 1, true},
    {CONFIG_GENERAL_ENABLE_MUSIC_RANDOMISE, "enable_music_randomise", "Randomise city music", "General Settings / Audio Options", 0, 0, 1, 1, true},
    {CONFIG_GENERAL_ENABLE_VIDEO_SOUND, "enable_audio_in_videos", "Enable video sound", "General Settings / Audio Options", 1, 0, 1, 1, true},
    {CONFIG_GENERAL_VIDEO_VOLUME, "video_volume", "Video volume (%)", "General Settings / Audio Options", 100, 0, 100, 1, true},
    {CONFIG_GENERAL_NEXT_AUTOSAVE_SLOT, "next_autosave_slot", "Next autosave slot", "General Settings / General", 0, 0, 1, 1, false},
    {CONFIG_GENERAL_HAS_SET_USER_DIRECTORIES, "has_set_user_directories", "Has set user directories", "General Settings / General", 1, 0, 1, 1, false},
    {CONFIG_GP_FIX_IMMIGRATION_BUG, "gameplay_fix_immigration", "Fix immigration", "City Management / General", 0, 0, 1, 1, true},
    {CONFIG_GP_FIX_100_YEAR_GHOSTS, "gameplay_fix_100y_ghosts", "Fix 100y ghosts", "City Management / General", 0, 0, 1, 1, true},
    {CONFIG_SCREEN_DISPLAY_SCALE, "screen_display_scale", "Display scale:", "General Settings / Video Options", 100, 50, 500, 5, true},
    {CONFIG_SCREEN_CURSOR_SCALE, "screen_cursor_scale", "Cursor scale:", "General Settings / Video Options", 100, 100, 200, 50, true},
    {CONFIG_SCREEN_COLOR_CURSORS, "screen_color_cursors", "Use colored cursors", "General Settings / Video Options", 0, 0, 1, 1, true},
    {CONFIG_UI_SIDEBAR_INFO, "ui_sidebar_info", "Extra information in the control panel", "User Interface / General", 1, 0, 1, 1, true},
    {CONFIG_UI_SHOW_INTRO_VIDEO, "ui_show_intro_video", "Play intro videos", "User Interface / General", 0, 0, 1, 1, true},
    {CONFIG_UI_SMOOTH_SCROLLING, "ui_smooth_scrolling", "Enable smooth scrolling", "User Interface / Scrolling", 1, 0, 1, 1, true},
    {CONFIG_UI_DISABLE_MOUSE_EDGE_SCROLLING, "ui_disable_mouse_edge_scrolling", "Disable map scrolling on window edge", "User Interface / Scrolling", 0, 0, 1, 1, true},
    {CONFIG_UI_VISUAL_FEEDBACK_ON_DELETE, "ui_visual_feedback_on_delete", "Visual feedback on delete", "User Interface / General", 0, 0, 1, 1, true},
    {CONFIG_UI_ALLOW_CYCLING_TEMPLES, "ui_allow_cycling_temples", "Allow cycling temples", "User Interface / General", 0, 0, 1, 1, true},
    {CONFIG_UI_SHOW_WATER_STRUCTURE_RANGE, "ui_show_water_structure_range", "Show range when building reservoirs, fountains and wells", "User Interface / Building", 1, 0, 1, 1, true},
    {CONFIG_UI_SHOW_WATER_STRUCTURE_RANGE_HOUSES, "ui_show_water_structure_range_houses", "Show range of fountains and wells when building houses", "User Interface / Building", 0, 0, 1, 1, true},
    {CONFIG_UI_SHOW_MARKET_RANGE, "ui_show_market_range", "Show range when building markets", "User Interface / Building", 0, 0, 1, 1, true},
    {CONFIG_UI_SHOW_CONSTRUCTION_SIZE, "ui_show_construction_size", "Show area of construction when dragging the cursor", "User Interface / Building", 1, 0, 1, 1, true},
    {CONFIG_UI_HIGHLIGHT_LEGIONS, "ui_highlight_legions", "Highlight legion on cursor hover", "User Interface / Building", 1, 0, 1, 1, true},
    {CONFIG_UI_SHOW_MILITARY_SIDEBAR, "ui_show_military_sidebar", "Enable military sidebar", "User Interface / Building", 0, 0, 1, 1, true},
    {CONFIG_UI_DISABLE_RIGHT_CLICK_MAP_DRAG, "ui_disable_map_drag", "Disable dragging with right mouse button", "User Interface / Scrolling", 0, 0, 1, 1, true},
    {CONFIG_UI_SHOW_MAX_PROSPERITY, "ui_show_max_prosperity", "Display max attainable prosperity rating with current housing", "User Interface / General", 0, 0, 1, 1, true},
    {CONFIG_UI_DIGIT_SEPARATOR, "ui_digit_separator", "Separate digits", "User Interface / General", 0, 0, 1, 1, true},
    {CONFIG_UI_INVERSE_MAP_DRAG, "ui_inverse_map_drag", "Inverse dragging map with right mouse button", "User Interface / Scrolling", 0, 0, 1, 1, true},
    {CONFIG_UI_MESSAGE_ALERTS, "ui_message_alerts", "Show new messages as alerts instead of popups", "User Interface / General", 0, 0, 1, 1, true},
    {CONFIG_UI_SHOW_GRID, "ui_show_grid", "Show grid", "User Interface / Building", 0, 0, 1, 1, true},
    {CONFIG_UI_SHOW_PARTIAL_GRID_AROUND_CONSTRUCTION, "ui_show_partial_grid_around_construction", "Show partial grid around construction", "User Interface / Building", 0, 0, 1, 1, true},
    {CONFIG_UI_ALWAYS_SHOW_ROTATION_BUTTONS, "ui_always_show_rotation_buttons", "Always show rotation buttons", "User Interface / Building", 0, 0, 1, 1, true},
    {CONFIG_UI_SHOW_ROAMING_PATH, "ui_show_roaming_path", "Preview paths traveled by roaming walkers", "User Interface / Building", 0, 0, 1, 1, true},
    {CONFIG_UI_DRAW_CLOUD_SHADOWS, "ui_draw_cloud_shadows", "Draw cloud shadows", "User Interface / Weather", 0, 0, 1, 1, true},
    {CONFIG_UI_DISPLAY_FPS, "ui_display_fps", "Display fps", "User Interface / General", 0, 0, 1, 1, true},
    {CONFIG_UI_ASK_CONFIRMATION_ON_FILE_OVERWRITE, "ui_ask_confirmation_on_file_overwrite", "Ask for confirmation when overwriting a file", "User Interface / General", 1, 0, 1, 1, true},
    {CONFIG_GP_CH_MAX_GRAND_TEMPLES, "gameplay_change_max_grand_temples", "Maximum number of grand temples per city:", "Difficulty / General", 2, 0, 5, 1, true},
    {CONFIG_GP_CH_JEALOUS_GODS, "gameplay_change_jealous_gods", "Disable jealousy of gods", "Difficulty / General", 0, 0, 1, 1, true},
    {CONFIG_GP_CH_GLOBAL_LABOUR, "gameplay_change_global_labour", "Enable global labor pool", "Difficulty / General", 0, 0, 1, 1, true},
    {CONFIG_GP_CH_RETIRE_AT_60, "gameplay_change_retire_at_60", "Retire at 60", "City Management / General", 0, 0, 1, 1, false},
    {CONFIG_GP_CH_FIXED_WORKERS, "gameplay_change_fixed_workers", "Fixed worker pool - 38% of plebeian population", "Difficulty / General", 0, 0, 1, 1, true},
    {CONFIG_GP_CH_WOLVES_BLOCK, "gameplay_wolves_block", "Block building around wolves", "Difficulty / General", 0, 0, 1, 1, true},
    {CONFIG_GP_CH_NO_SUPPLIER_DISTRIBUTION, "gameplay_buyers_dont_distribute", "Market buyers don't distribute goods to houses", "City Management / Storage and Markets", 0, 0, 1, 1, true},
    {CONFIG_GP_CH_GETTING_GRANARIES_GO_OFFROAD, "gameplay_change_getting_granaries_go_offroad", "Cart pushers from getting granaries can go off-road", "City Management / Roads", 0, 0, 1, 1, true},
    {CONFIG_GP_CH_GRANARIES_GET_DOUBLE, "gameplay_change_granaries_get_double", "Double the capacity of cart pushers from getting granaries", "City Management / Storage and Markets", 0, 0, 1, 1, true},
    {CONFIG_GP_CH_ALLOW_EXPORTING_FROM_GRANARIES, "gameplay_change_allow_exporting_from_granaries", "Allow traders to export food from granaries", "City Management / Storage and Markets", 0, 0, 1, 1, true},
    {CONFIG_GP_CH_TOWER_SENTRIES_GO_OFFROAD, "gameplay_change_tower_sentries_go_offroad", "Tower sentries don't need road access from barracks", "City Management / Roads", 0, 0, 1, 1, true},
    {CONFIG_GP_CH_FARMS_DELIVER_CLOSE, "gameplay_change_farms_deliver_close", "Farms and wharves deliver only to nearby granaries", "City Management / Storage and Markets", 0, 0, 1, 1, true},
    {CONFIG_GP_CH_DELIVER_ONLY_TO_ACCEPTING_GRANARIES, "gameplay_change_only_deliver_to_accepting_granaries", "Food isn't delivered to getting granaries", "City Management / Storage and Markets", 0, 0, 1, 1, true},
    {CONFIG_GP_CH_ALL_HOUSES_MERGE, "gameplay_change_all_houses_merge", "All houses merge", "City Management / Housing", 0, 0, 1, 1, true},
    {CONFIG_GP_CH_RANDOM_COLLAPSES_TAKE_MONEY, "gameplay_change_random_mine_or_pit_collapses_take_money", "Randomly collapsing pits and mines take some money instead", "Difficulty / General", 0, 0, 1, 1, true},
    {CONFIG_GP_CH_MULTIPLE_BARRACKS, "gameplay_change_multiple_barracks", "Multiple barracks", "City Management / General", 0, 0, 1, 1, false},
    {CONFIG_GP_CH_WAREHOUSES_DONT_ACCEPT, "gameplay_change_warehouses_dont_accept", "Warehouses and granaries don't accept anything when built", "City Management / Storage and Markets", 0, 0, 1, 1, true},
    {CONFIG_GP_CH_MARKETS_DONT_ACCEPT, "gameplay_change_markets_dont_accept", "Markets don't accept anything when built", "City Management / Storage and Markets", 0, 0, 1, 1, true},
    {CONFIG_GP_CH_WAREHOUSES_GRANARIES_OVER_ROAD_PLACEMENT, "gameplay_change_warehouses_granaries_over_road_placement", "Warehouses and granaries can be built over any roads", "City Management / Roads", 0, 0, 1, 1, true},
    {CONFIG_GP_CH_HOUSES_DONT_EXPAND_INTO_GARDENS, "gameplay_change_houses_dont_expand_into_gardens", "Houses don't expand into gardens", "City Management / Housing", 0, 0, 1, 1, true},
    {CONFIG_GP_CH_MONUMENTS_BOOST_CULTURE_RATING, "gameplay_change_monuments_boost_culture_rating", "Monuments boost culture rating", "City Management / General", 0, 0, 1, 1, true},
    {CONFIG_GP_CH_DISABLE_INFINITE_WOLVES_SPAWNING, "gameplay_change_disable_infinite_wolves_spawning", "Disable infinite wolves spawning", "Difficulty / General", 0, 0, 1, 1, true},
    {CONFIG_GP_CH_ROAMERS_DONT_SKIP_CORNERS, "gameplay_change_romers_dont_skip_corners", "Roaming walkers don't skip corners", "City Management / Roads", 0, 0, 1, 1, true},
    {CONFIG_GP_CH_YEARLY_AUTOSAVE, "gameplay_change_yearly_autosave", "Yearly autosave ON", "General Settings / General", 0, 0, 1, 1, true},
    {CONFIG_GP_CH_AUTO_KILL_ANIMALS, "gameplay_change_auto_kill_animals", "Citizens will automatically kill harmless animals", "Difficulty / General", 0, 0, 1, 1, true},
    {CONFIG_GP_CH_GATES_DEFAULT_TO_PASS_ALL_WALKERS, "gameplay_change_nonmilitary_gates_allow_walkers", "Non-military gates default to allowing all walkers", "City Management / Roadblocks", 0, 0, 1, 1, true},
    {CONFIG_GP_CH_MAX_AUTOSAVE_SLOTS, "gameplay_change_max_autosave_slots", "Maximum number of yearly autosave slots:", "General Settings / General", 10, 1, 20, 1, true},
    {CONFIG_UI_SHOW_SPEEDRUN_INFO, "ui_show_speedrun_info", "Show speedrun info", "User Interface / General", 0, 0, 1, 1, true},
    {CONFIG_UI_SHOW_DESIRABILITY_RANGE, "ui_show_desirability_range", "Show desirability when building religious or military structures", "User Interface / Building", 0, 0, 1, 1, true},
    {CONFIG_UI_SHOW_DESIRABILITY_RANGE_ALL, "ui_show_desirability_range_all", "Show desirability when building any structures", "User Interface / Building", 0, 0, 1, 1, true},
    {CONFIG_UI_DRAW_ASCLEPIUS, "ui_draw_asclepius", "Draw Rod of Asclepius for health menu", "User Interface / Building", 0, 0, 1, 1, true},
    {CONFIG_UI_HIGHLIGHT_SELECTED_BUILDING, "ui_highlight_selected_building", "Highlight selected building", "User Interface / Building", 1, 0, 1, 1, true},
    {CONFIG_GP_CARAVANS_MOVE_OFF_ROAD, "gameplay_change_caravans_move_off_road", "Trade caravans and ox carts do not prioritize road networks", "City Management / Roads", 0, 0, 1, 1, true},
    {CONFIG_UI_DRAW_WEATHER, "ui_draw_weather", "Enable dynamic weather", "User Interface / Weather", 1, 0, 1, 1, true},
    {CONFIG_GP_STORAGE_INCREMENT_4, "gameplay_change_storage_step_4", "Use multiples of 4 for granary, warehouse and cart depot quantity", "City Management / Storage and Markets", 0, 0, 1, 1, true},
    {CONFIG_UI_MOVE_SAVINGS_TO_RIGHT, "ui_move_savings_to_right", "Original top bar items order", "User Interface / Building", 0, 0, 1, 1, true},
    {CONFIG_GP_CH_PATRICIAN_DEVOLUTION_FIX, "gameplay_patrician_devolution_fix", "Patrician houses maintain integrity when devolving", "City Management / Housing", 1, 0, 1, 1, true},
    {CONFIG_WT_SNOW_INTENSITY, "weather_snow_intensity", "Snow overlay intensity (%)", "User Interface / Weather", 30, 0, 100, 5, true},
    {CONFIG_WT_RAIN_INTENSITY, "weather_rain_intensity", "Rain overlay intensity (%)", "User Interface / Weather", 60, 0, 100, 5, true},
    {CONFIG_WT_SANDSTORM_INTENSITY, "weather_sandstorm_intensity", "Sandstorm overlay intensity (%)", "User Interface / Weather", 10, 0, 100, 5, true},
    {CONFIG_WT_RAIN_SPEED, "weather_rain_speed", "Raindrop speed", "User Interface / Weather", 2, 0, 4, 1, true},
    {CONFIG_WT_RAIN_LENGTH, "weather_rain_length", "Raindrop size", "User Interface / Weather", 2, 0, 4, 1, true},
    {CONFIG_WT_SNOW_SPEED, "weather_snow_speed", "Snowflake speed", "User Interface / Weather", 1, 0, 4, 1, true},
    {CONFIG_WT_SANDSTORM_SPEED, "weather_sandstorm_speed", "Sand speed", "User Interface / Weather", 0, 0, 4, 1, true},
    {CONFIG_UI_EMPIRE_SIDEBAR_WIDTH, "ui_empire_sidebar_width", "Empire sidebar width (%)", "User Interface / Empire", 25, 0, 50, 1, true},
    {CONFIG_GP_CH_DEFAULT_GAME_SPEED, "gameplay_change_default_game_speed", "Default game speed (index: 0 = 10%, 7 = 80%, 14 = 1000%)", "General Settings / General", 7, 0, 14, 1, true},
    {CONFIG_UI_SHOW_CUSTOM_VARIABLES, "ui_show_custom_variables", "Show custom variables in city view", "User Interface / Building", 1, 0, 1, 1, true},
    {CONFIG_GP_CH_ENABLE_GETTING_WHILE_STOCKPILED, "gameplay_change_stockpiled_getting", "Enable 'Getting' while a resource is stockpiled", "City Management / Storage and Markets", 0, 0, 1, 1, true},
    {CONFIG_UI_PAVED_ROADS_NEAR_GRANNARIES, "ui_paved_roads_near_grannaries", "Pave roads next to granaries", "User Interface / Building", 1, 0, 1, 1, true},
    {CONFIG_UI_ANIMATE_TRADE_ROUTES, "ui_animate_trade_routes", "Animate trade routes", "User Interface / Empire", 1, 0, 1, 1, true},
    {CONFIG_UI_MOVE_LEGION_SOUND_SWAP, "ui_move_legion_sound_swap", "Alternative legion move sound", "General Settings / Audio Options", 0, 0, 1, 1, true},
    {CONFIG_GP_CH_CART_DEPOT_ADVANCED, "gameplay_change_cart_depot_advanced_settings", "Enable advanced cart depot orders", "City Management / Storage and Markets", 1, 0, 1, 1, true},
    {CONFIG_UI_CART_DEPOT_TOOLTIP_STYLE, "ui_cart_depot_tooltip_style", "Cart depot tooltip style", "City Management / Storage and Markets", 1, 0, 2, 1, true},
    {CONFIG_DEBUG_START_WITH_TOOLTIP, "debug_start_with_tooltip", "Debug start with tooltip", "Diagnostics", 0, 0, 1, 1, true},
    {CONFIG_UI_CLEAR_WARNINGS_RIGHTCLICK, "ui_clear_warnings_rightclick", "Right click to clear warnings in city view", "User Interface / Building", 1, 0, 1, 1, true},
    {CONFIG_GP_CH_STORAGE_REQUESTS_RESPECT_MAINTAIN, "gp_ch_storage_requests_respect_maintain", "Caesar's requests respect 'Maintaining'", "City Management / Storage and Markets", 1, 0, 1, 1, true},
    {CONFIG_GP_CH_MARKET_RANGE, "gameplay_market_range", "Limit market buyer range", "City Management / Storage and Markets", 1, 0, 1, 1, true},
    {CONFIG_UI_CV_BUILD_MENU_ICONS, "ui_cv_build_menu_icons", "Show resource icons in build menu", "User Interface / Building", 1, 0, 1, 1, true},
    {CONFIG_UI_WT_ENABLE_SNOW_CENTRAL, "ui_wt_enable_snow_central", "Enable snow in central climate", "User Interface / Weather", 0, 0, 1, 1, true},
    {CONFIG_UI_CV_CURSOR_SHADOW, "ui_cv_cursor_shadow", "Enable cursor shadow", "User Interface / Building", 1, 0, 1, 1, true},
    {CONFIG_GENERAL_UNLOCK_MOUSE, "general_unlock_mouse", "Lock mouse in Fullscreen mode", "General Settings / Video Options", 1, 0, 1, 1, true},
    {CONFIG_GP_CH_HOUSING_PRE_MERGE_VACANT_LOTS, "gp_ch_housing_pre_merge_vacant_lots", "Houses always merge in 2x2", "City Management / Housing", 1, 0, 1, 1, true},
    {CONFIG_UI_BUILD_SHOW_RESERVOIR_RANGES, "ui_build_show_reservoir_ranges", "Show reservoir range when building other reservoirs and buildings that require its coverage", "User Interface / Building", 1, 0, 1, 1, true},
    {CONFIG_UI_EMPIRE_SMART_BORDER_PLACMENT, "ui_empire_smart_border_placement", "Enable smart border placement", "User Interface / Empire", 1, 0, 1, 1, true},
    {CONFIG_GP_CH_ALWAYS_DESTROY_BRIDGES, "always_be_able_to_destroy_bridges", "Always allow removal of bridges", "City Management / Destruction", 0, 0, 1, 1, true},
    {CONFIG_UI_ENABLE_BUILD_MENU_SHORTCUTS, "ui_enable_build_menu_shortcuts", "Enable build menu shortcuts", "User Interface / Building", 0, 0, 1, 1, true},
    {CONFIG_UI_EMPIRE_CLICK_TO_DELETE, "ui_empire_must_click_to_delete", "Must click to delete object", "User Interface / Empire", 0, 0, 1, 1, true},
    {CONFIG_UI_EMPIRE_CONFIRM_DELETE, "ui_empire_confirm_deletion", "Confirm object deletion", "User Interface / Empire", 1, 0, 1, 1, true},
    {CONFIG_UI_WT_PREVIEW_RAIN, "ui_wt_preview_rain", "Preview Rain", "User Interface / Weather", 0, 0, 1, 1, true},
    {CONFIG_UI_WT_PREVIEW_SNOW, "ui_wt_snow_preview", "Preview Snow", "User Interface / Weather", 0, 0, 1, 1, true},
    {CONFIG_UI_WT_PREVIEW_SANDSTORM, "ui_wt_sandstorm_preview", "Preview Sandstorm", "User Interface / Weather", 0, 0, 1, 1, true},
    {CONFIG_UI_WT_PREVIEW_HEAVY_RAIN, "ui_wt_preview_heavy_rain", "Preview Heavy Rain", "User Interface / Weather", 0, 0, 1, 1, true},
    {CONFIG_UI_WT_SANDSTORM_SIZE, "ui_wt_sandstorm_size", "Sand size", "User Interface / Weather", 0, 0, 4, 1, true},
    {CONFIG_UI_WT_SNOWFLAKE_SIZE, "ui_wt_snowflake_size", "Snowflake size", "User Interface / Weather", 2, 0, 4, 1, true},
    {CONFIG_UI_WT_WEATHER_DURATION, "ui_wt_weather_duration", "Weather duration", "User Interface / Weather", 1, 0, 2, 1, true},
    {CONFIG_GP_CH_GRANARY_DEFAULT_TO_PASS_ALL_WALKERS, "gameplay_change_granary_do_not_allow_walkers", "Granaries do not allow walkers by default", "City Management / Roadblocks", 0, 0, 1, 1, true},
    {CONFIG_GP_CH_WAREHOUSE_DEFAULT_TO_PASS_ALL_WALKERS, "gameplay_change_warehouse_do_not_allow_walkers", "Warehouses do not allow walkers by default", "City Management / Roadblocks", 0, 0, 1, 1, true},
    {CONFIG_SCALE_FILTER, "scale_filter", "Image scaling filter", "General Settings / Video Options", 0, 0, 3, 1, true},
    {CONFIG_DEBUG, "debug", "Debug", "Diagnostics", 0, 0, 1, 1, true},
    {CONFIG_DEBUG_PERFORMANCE_TRACKER, "debug_performance_tracker", "Debug performance tracker", "Diagnostics", 0, 0, 1, 1, true},
    {CONFIG_UI_AUTO_DELETE_OLD_COMMON_MESSAGES, "ui_auto_delete_old_common_messages", "Auto delete old common messages", "User Interface / General", 0, 0, 1, 1, true},
    {CONFIG_UI_EXTENDED_CAMERA_BOUNDS, "ui_extended_camera_bounds", "Extended camera bounds", "User Interface / General", 0, 0, 1, 1, true},
    {CONFIG_UI_EMPIRE_SIDEBAR_SORT_METHOD, "ui_empire_sidebar_sort_method", "Empire city sort order", "User Interface / Empire", 0, 0, 4, 1, true},
    {CONFIG_UI_EMPIRE_SIDEBAR_SORT_REVERSED, "ui_empire_sidebar_sort_reversed", "Empire sidebar sort reversed", "User Interface / Empire", 0, 0, 1, 1, true},
    {CONFIG_UI_CLIMATE_GRID_COLORS, "ui_climate_grid_colors", "Climate grid colors", "User Interface / General", 0, 0, 1, 1, true},
    {CONFIG_UI_SHOW_SHORELINE_DESIRABILITY, "ui_show_shoreline_desirability", "Show shoreline desirability", "User Interface / General", 1, 0, 1, 1, true},
    {CONFIG_UI_SHOW_ELEVATION_DESIRABILITY, "ui_show_elevation_desirability", "Show elevation desirability", "User Interface / General", 1, 0, 1, 1, true},
};
static_assert(std::size(config_options) == CONFIG_MAX_ENTRIES);
inline constexpr bool config_option_order_valid()
{
    for (int i = 0; i < CONFIG_MAX_ENTRIES; ++i) if (config_options[i].id != i) return false;
    return true;
}
static_assert(config_option_order_valid());
