#pragma once

#include "translation/translation.h"

#include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif

typedef struct warning_type {
    const char *name;
} warning_type;

#ifdef __cplusplus
}
#endif

#ifdef __cplusplus
#define DECLARE_WARNING_TYPE(name) inline constexpr warning_type name{#name}
#else
#define DECLARE_WARNING_TYPE(name) static const warning_type name = {#name}
#endif

static const warning_type WARNING_NONE = {0};

DECLARE_WARNING_TYPE(WARNING_ORIENTATION);
DECLARE_WARNING_TYPE(WARNING_CLEAR_LAND_NEEDED);
DECLARE_WARNING_TYPE(WARNING_OUT_OF_MONEY);
DECLARE_WARNING_TYPE(WARNING_ONE_BUILDING_OF_TYPE);
DECLARE_WARNING_TYPE(WARNING_ROAD_ACCESS_NEEDED);
DECLARE_WARNING_TYPE(WARNING_NOT_AVAILABLE);
DECLARE_WARNING_TYPE(WARNING_NOT_AVAILABLE_YET);
DECLARE_WARNING_TYPE(WARNING_MARBLE_NEEDED_LARGE_TEMPLE);
DECLARE_WARNING_TYPE(WARNING_MARBLE_NEEDED_ORACLE);
DECLARE_WARNING_TYPE(WARNING_WORKERS_NEEDED);
DECLARE_WARNING_TYPE(WARNING_MORE_FOOD_NEEDED);
DECLARE_WARNING_TYPE(WARNING_BUILD_MARKET);
DECLARE_WARNING_TYPE(WARNING_MEADOW_NEEDED);
DECLARE_WARNING_TYPE(WARNING_WATER_NEEDED);
DECLARE_WARNING_TYPE(WARNING_ROCK_NEEDED);
DECLARE_WARNING_TYPE(WARNING_TREE_NEEDED);
DECLARE_WARNING_TYPE(WARNING_SHORE_NEEDED);
DECLARE_WARNING_TYPE(WARNING_OPEN_TRADE_TO_IMPORT);
DECLARE_WARNING_TYPE(WARNING_TRADE_IMPORT_RESOURCE);
DECLARE_WARNING_TYPE(WARNING_WATER_PIPE_ACCESS_NEEDED);
DECLARE_WARNING_TYPE(WARNING_PLACE_RESERVOIR_NEXT_TO_WATER);
DECLARE_WARNING_TYPE(WARNING_CONNECT_TO_RESERVOIR);
DECLARE_WARNING_TYPE(WARNING_SENTRIES_NEED_WALL);
DECLARE_WARNING_TYPE(WARNING_BUILD_BARRACKS);
DECLARE_WARNING_TYPE(WARNING_WEAPONS_NEEDED);
DECLARE_WARNING_TYPE(WARNING_BUILD_ACTOR_COLONY);
DECLARE_WARNING_TYPE(WARNING_BUILD_GLADIATOR_SCHOOL);
DECLARE_WARNING_TYPE(WARNING_BUILD_LION_HOUSE);
DECLARE_WARNING_TYPE(WARNING_BUILD_CHARIOT_MAKER);
DECLARE_WARNING_TYPE(WARNING_WALL_NEEDED);
DECLARE_WARNING_TYPE(WARNING_ENEMY_NEARBY);
DECLARE_WARNING_TYPE(WARNING_LEGION_MORALE_TOO_LOW);
DECLARE_WARNING_TYPE(WARNING_MAX_LEGIONS_REACHED);
DECLARE_WARNING_TYPE(WARNING_PEOPLE_ON_BRIDGE);
DECLARE_WARNING_TYPE(WARNING_DOCK_OPEN_WATER_NEEDED);
DECLARE_WARNING_TYPE(WARNING_EDITOR_NEED_MAP_EDGE);
DECLARE_WARNING_TYPE(WARNING_EDITOR_NEED_OPEN_WATER);
DECLARE_WARNING_TYPE(WARNING_EDITOR_CANNOT_PLACE);
DECLARE_WARNING_TYPE(WARNING_EDITOR_NO_EARTHQUAKE_SCHEDULED);
DECLARE_WARNING_TYPE(WARNING_HOUSE_TOO_FAR_FROM_ROAD);
DECLARE_WARNING_TYPE(WARNING_CITY_BOXED_IN);
DECLARE_WARNING_TYPE(WARNING_CITY_BOXED_IN_PEOPLE_WILL_PERISH);
DECLARE_WARNING_TYPE(WARNING_DATA_LIMIT_REACHED);
DECLARE_WARNING_TYPE(WARNING_NO_MESS_HALL);
DECLARE_WARNING_TYPE(WARNING_MAX_GRAND_TEMPLES);
DECLARE_WARNING_TYPE(WARNING_WATER_NEEDED_FOR_BUILDING);
DECLARE_WARNING_TYPE(WARNING_RESOURCES_NOT_AVAILABLE);
DECLARE_WARNING_TYPE(WARNING_VARIANT_TOGGLE);
DECLARE_WARNING_TYPE(WARNING_SECESSION);
DECLARE_WARNING_TYPE(WARNING_WAREHOUSE_BREAKIN);
DECLARE_WARNING_TYPE(WARNING_GRANARY_BREAKIN);
DECLARE_WARNING_TYPE(WARNING_THEFT);
DECLARE_WARNING_TYPE(WARNING_WOLF_NEARBY);
DECLARE_WARNING_TYPE(WARNING_BET_VICTORY);
DECLARE_WARNING_TYPE(WARNING_BET_DEFEAT);
DECLARE_WARNING_TYPE(WARNING_DATA_COPY_SUCCESS);
DECLARE_WARNING_TYPE(WARNING_DATA_COPY_NOT_SUPPORTED);
DECLARE_WARNING_TYPE(WARNING_DATA_PASTE_SUCCESS);
DECLARE_WARNING_TYPE(WARNING_DATA_PASTE_FAILURE);
DECLARE_WARNING_TYPE(WARNING_DATA_MOTHBALL_ON);
DECLARE_WARNING_TYPE(WARNING_DATA_MOTHBALL_OFF);
DECLARE_WARNING_TYPE(WARNING_MISSING_RESOURCE);
DECLARE_WARNING_TYPE(WARNING_MISSING_PRODUCER);
DECLARE_WARNING_TYPE(WARNING_SENATE_NEEDED);
DECLARE_WARNING_TYPE(WARNING_BUILD_SENATE);
DECLARE_WARNING_TYPE(WARNING_NO_ARMOURY);
DECLARE_WARNING_TYPE(WARNING_WAREHOUSE_TOWER);
DECLARE_WARNING_TYPE(WARNING_REPAIR_IMPOSSIBLE);
DECLARE_WARNING_TYPE(WARNING_REPAIR_BURNING);
DECLARE_WARNING_TYPE(WARNING_REPAIR_MONUMENT);
DECLARE_WARNING_TYPE(WARNING_REPAIR_AQUEDUCT);
DECLARE_WARNING_TYPE(WARNING_DEPOT_CART_PUSHER_RECALL_ALL);
DECLARE_WARNING_TYPE(WARNING_DEPOT_RESOURCE_CHANGE);
DECLARE_WARNING_TYPE(WARNING_BUILDING_ROTATION);
DECLARE_WARNING_TYPE(WARNING_SCREENSHOT_SAVED);
DECLARE_WARNING_TYPE(WARNING_CONSOLE_COMMAND);
DECLARE_WARNING_TYPE(WARNING_CHEAT);
DECLARE_WARNING_TYPE(WARNING_MESSAGE_ALERT);
DECLARE_WARNING_TYPE(WARNING_ZOOM);

#undef DECLARE_WARNING_TYPE

#ifdef __cplusplus
extern "C" {
#endif

int city_warning_show(warning_type warning, const uint8_t *text);
int city_warning_show_translated(warning_type warning);
const uint8_t *city_warning_get_text(warning_type warning);

int city_has_warnings(void);

const uint8_t *city_warning_get(int position);

void city_warning_clear(warning_type warning);
void city_warning_clear_all(void);
void city_warning_clear_outdated(void);

#ifdef __cplusplus
}
#endif
