"""Generate pure archive-layout visitors from the pinned SB03 Git inventory."""
import json
import re
from inventory_augustus_save_schemas import ROOT, git, function


def main():
    inventory = json.loads((ROOT / 'docs/augustus_save_schema_inventory.json').read_text(encoding='utf-8'))
    output = ['// Generated by tools/generate_augustus_archive_layouts.py; upstream GPL source attribution is retained in the inventory.',
              '#pragma once', '#include <cstdint>', '#include <cstddef>', 'namespace augustus_archive_layouts {']
    for index, (identity, layout) in enumerate(inventory['layouts'].items()):
        producer = next(p for p in inventory['producers'] if p['layout'] == identity)
        revision = producer['commit']
        io = git('show', revision + ':src/game/file_io.c')
        scenario = git('show', revision + ':src/scenario/scenario.c')
        versions = git('show', revision + ':src/game/save_version.h')
        enum_text = '\n'.join(re.findall(r'typedef enum\s*\{.*?\}\s*\w+;', versions, re.S))
        enum_text = re.sub(r'}\s*\w+;', '};', enum_text).replace('typedef enum', 'enum')
        end = io.index('} savegame_version_data;') + len('} savegame_version_data;')
        struct = io[io.rfind('typedef struct', 0, end):end]
        offsets = re.search(r'static struct \{.*?\} buffer_offsets;', scenario, re.S).group().replace('static struct', 'struct')
        offsets = offsets.replace('savegame_version_t', 'int')
        calc = function(scenario, 'calculate_buffer_offsets')
        calc = calc[calc.index('{') + 1:-1]
        calc = re.sub(r'\s*if \(buffer_offsets.version.*?\n    }', '', calc, count=1, flags=re.S)
        calc = calc.replace('memset(&buffer_offsets, 0, sizeof(buffer_offsets));', '')
        size = function(scenario, 'scenario_get_state_buffer_size_by_savegame_version')
        size = size.replace('int scenario_get_state_buffer_size_by_savegame_version(int savegame_version)\n{',
                            'static int scenario_size(int savegame_version)\n{\n' + offsets.replace('} buffer_offsets;', '} buffer_offsets{};') +
                            '\nauto calculate_buffer_offsets = [&](int scenario_version) {' + calc + '\n};')
        get = layout['get_version_data'].replace('savegame_version_t version)', 'int version, int resources, int foods)')
        get = get.replace('resource_total_mapped()', 'resources').replace('resource_total_food_mapped()', 'foods')
        get = get.replace('scenario_get_state_buffer_size_by_savegame_version(version)', 'scenario_size(version)')
        visit = layout['init_savegame_data']
        visit = visit.replace('static void init_savegame_data(savegame_version_t version)', 'template <typename Emit> static void visit(int version, int resources, int foods, Emit emit)')
        visit = visit.replace('    clear_savegame_pieces();', '').replace('savegame_version_data version_data;', 'savegame_version_data version_data{};')
        visit = visit.replace('get_version_data(&version_data, version);', 'get_version_data(&version_data, version, resources, foods);')
        visit = re.sub(r'    savegame_state \*state = .*?\n    memset\(state, 0, sizeof\(\*state\)\);', '', visit, flags=re.S)
        visit = re.sub(r'    savegame_state \*state = [^;]*;', '', visit)
        visit = re.sub(r'state->(\w+) = create_savegame_piece\((.*?), ([01])\);', r'emit("\1", \2, \3);', visit)
        code = f'\n// Producer {revision}; layout {identity}\nnamespace layout_{index} {{\n' + enum_text + '\n' + struct + '\n' + size + '\n' + get + '\n' + visit + '\n}\n'
        constants = {'PIECE_SIZE_DYNAMIC': 0, 'GRID_SIZE_BUF_U8': 162*162, 'GRID_SIZE_BUF_U16': 162*162*2,
                     'GRID_SIZE_BUF_U32': 162*162*4, 'RESOURCE_MAX_LEGACY': 16, 'RESOURCE_MAX_FOOD_LEGACY': 7}
        for path in ('src/scenario/data.h', 'src/scenario/request.h', 'src/scenario/invasion.h',
                     'src/scenario/allowed_building.h', 'src/scenario/custom_variable.h',
                     'src/scenario/demand_change.h', 'src/scenario/price_change.h', 'src/figure/enemy_army.h', 'src/core/file.h'):
            text = git('show', revision + ':' + path)
            constants.update({k: int(v) for k, v in re.findall(r'(?m)^#define\s+(\w+)\s+(\d+)\s*$', text)})
        code = code.replace('sizeof(scenario.empire.custom_name)', str(constants['FILE_NAME_MAX']))
        for name, value in constants.items():
            code = re.sub(r'\b' + name + r'\b', str(value), code)
        unresolved = sorted(set(re.findall(r'\b(?:MAX_|RESOURCE_MAX_|GRID_SIZE)\w*', code)))
        if unresolved:
            raise ValueError(unresolved)
        output.append(code)
    output.append('} // namespace augustus_archive_layouts\n')
    target = ROOT / 'src/game/augustus_archive_layouts.generated.h'
    target.write_text('\n'.join(output), encoding='utf-8')
    print(f'Generated {len(inventory["layouts"])} pure visitors ({target.stat().st_size} bytes)')


if __name__ == '__main__':
    main()
