"""Pin source defaults for the shared pre-fork save bridge, never runtime definitions."""
import re
import subprocess
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SOURCE = "caa61f5ceca8cf19e1caa785e9af2a55859c52cb"
FIELDS = ("cost", "desirability_value", "desirability_step", "desirability_step_size", "desirability_range", "laborers")


def read_models(revision):
    def source(path):
        return subprocess.check_output(["git", "show", f"{revision}:{path}"], cwd=ROOT, text=True)
    enums = {name: int(value) for name, value in re.findall(r"(BUILDING_\w+)\s*=\s*(\d+)", source("src/building/type.h"))}
    text = source("src/building/properties.c")
    fixed_tools = "if (((props->size && props->event_data.attr)" in text
    text = text[text.index("static building_properties properties["):text.index("static model_building NOTHING")]
    models = [[0] * 6 for _ in range(enums["BUILDING_TYPE_MAX"])]
    entries = re.split(r"(?m)^[ \t]+\[(BUILDING_\w+)\] = \{", text)
    for name, body in zip(entries[1::2], entries[2::2]):
        # Match the producer's model_reset eligibility, including its two exclusions.
        eligible = re.search(r"\.size\s*=\s*[1-9]", body) and ".event_data.attr" in body and name not in ("BUILDING_GRAND_GARDEN", "BUILDING_DOLPHIN_FOUNTAIN")
        if not eligible and not (fixed_tools and name in ("BUILDING_CLEAR_LAND", "BUILDING_REPAIR_LAND", "BUILDING_CLEAR_TREES")):
            continue
        block = re.search(r"\.building_model_data\s*=\s*\{([^}]+)\}", body)
        if not block:
            continue
        values = {key: int(value) for key, value in re.findall(r"\.(\w+)\s*=\s*(-?\d+)", block[1])}
        if set(values) != set(FIELDS):
            raise ValueError(f"Incomplete baseline: {name}")
        models[enums[name]] = [values[key] for key in FIELDS]
    assert models[31] == [50, 2, 1, -1, 2, 8]
    return models


def generate():
    models = read_models(SOURCE)
    early_native = read_models("b3afad0a7")
    assert early_native[:-1] == models and len(early_native) == 212
    # Save version 170 spans both these fixes without recording the producer
    # revision. Values matching an earlier default are ambiguous, not edits.
    variants = ("075ed783b", "991a8d6e2")
    alternatives = set()
    for revision in variants:
        earlier = read_models(revision)
        assert len(earlier) == len(models)
        for index, (old, new) in enumerate(zip(earlier, models)):
            for field, (old_value, new_value) in enumerate(zip(old, new)):
                if old_value != new_value:
                    alternatives.add((index, field, old_value))
    lines = ["// Generated by tools/generate_legacy_model_defaults.py from Augustus (GPL-3.0).", f"// Producer {SOURCE}. Import baseline only; active definitions always come from mods.", "#pragma once", '#include "building/properties.h"', "namespace legacy_model_defaults {", "inline constexpr model_building buildings[] = {"]
    lines.extend("    {" + ", ".join(map(str, values)) + "}, // " + str(index) for index, values in enumerate(models))
    lines.extend(["};", "// Early fork extension b3afad0a7: legacy ID 211 is clear_trees, not upstream highway_station.", "inline constexpr model_building clear_trees_extension = {" + ", ".join(map(str, early_native[-1])) + "};", "// Version 170 also shipped these defaults (075ed783b, 991a8d6e2).", "struct Alternative { size_t building; size_t field; int value; };", "inline constexpr Alternative version_170_alternatives[] = {"])
    lines.extend("    {" + ", ".join(map(str, entry)) + "}," for entry in sorted(alternatives))
    lines.extend(["};", "}", ""])
    (ROOT / "src/game/legacy_model_defaults.generated.h").write_text("\n".join(lines), encoding="utf-8")
    print(f"Generated {len(models)} shared-source model baselines")


if __name__ == "__main__":
    generate()


