"""Generate the reviewed producer baseline for scenario construction exceptions."""
import re
import subprocess
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
TARGET = "d879725d22dcf6cefdf84c75d84634d22645111d"


def source(revision, path):
    return subprocess.check_output(["git", "show", f"{revision}:{path}"], cwd=ROOT, text=True, encoding="utf-8")


def parse(revision):
    text = source(revision, "src/building/monument.c")
    names = ["none", "wheat", "vegetables", "fruit", "meat", "fish", "clay", "timber", "olives", "vines", "iron", "marble", "gold", "sand", "stone", "pottery", "furniture", "oil", "wine", "weapons", "concrete", "bricks"]
    slots = {"RESOURCE_" + name.upper(): index for index, name in enumerate(names)}
    slots["ARCHITECTS"] = 0
    templates = {}
    for name, body in re.findall(r"static const monument_type (\w+) = \{(.*?)\n\};", text, re.S):
        phases = int(re.search(r"\.phases\s*=\s*(\d+)", body)[1])
        rows = []
        for row in re.findall(r"\{([^{}]*)\}", body):
            values = [0] * 22
            for resource, value in re.findall(r"\[(\w+)\]\s*=\s*(\d+)", row):
                values[slots[resource]] = int(value)
            rows.append(values)
        assert len(rows) == phases <= 6
        rows.extend([[0] * 22 for _ in range(6 - len(rows))])
        templates[name] = (phases, rows)
    assignments = re.findall(r"MONUMENT_TYPES\[MONUMENT_(\w+)\] = (\w+);", text)
    assert len(assignments) == 21
    return [(name.lower(), *templates[template]) for name, template in assignments]


def main():
    baseline = parse(TARGET)
    assert baseline == parse("17b05668b"), "Review the changed producer defaults before generating"
    lines = ["// Augustus GPL-3.0 producer defaults; generated by tools/generate_augustus_monument_defaults.py.", f"// Reviewed from 17b05668b through {TARGET}.", "#pragma once", "namespace augustus_monument_defaults {", "struct Entry { const char *name; int phases; int resources[6][22]; };", "inline constexpr Entry entries[] = {"]
    for name, phases, rows in baseline:
        lines.append(f'    {{"{name}", {phases}, {{')
        lines.extend("        {" + ",".join(map(str, row)) + "}," for row in rows)
        lines.append("    }},")
    lines.extend(["};", "}", ""])
    (ROOT / "src/game/augustus_monument_defaults.generated.h").write_text("\n".join(lines), encoding="utf-8")


if __name__ == "__main__":
    main()
