"""Generate foreign producer baselines for recovering authored model exceptions."""
import re
import subprocess
from pathlib import Path
from generate_legacy_model_defaults import read_models

ROOT = Path(__file__).resolve().parents[1]
BASE = "caa61f5ceca8cf19e1caa785e9af2a55859c52cb"
TARGET = "d879725d22dcf6cefdf84c75d84634d22645111d"
HOUSE_FIELDS = ("devolve_desirability", "evolve_desirability", "entertainment", "water", "religion", "education", "barber", "bathhouse", "health", "food_types", "pottery", "oil", "furniture", "wine", "prosperity", "max_people", "tax_multiplier")


def git(*args):
    return subprocess.check_output(["git", *args], cwd=ROOT, text=True, encoding="utf-8")


def generate():
    changes = git("rev-list", "--reverse", "--first-parent", f"{BASE}..{TARGET}", "--", "src/building/properties.c", "src/building/type.h", "src/game/save_version.h").splitlines()
    revisions = [BASE, *changes]
    snapshots = []
    for revision in revisions:
        version = int(re.search(r"SAVE_GAME_CURRENT_VERSION\s*=\s*(0x[0-9a-f]+)", git("show", f"{revision}:src/game/save_version.h"))[1], 16)
        enums = {name: int(value) for name, value in re.findall(r"(BUILDING_\w+)\s*=\s*(\d+)", git("show", f"{revision}:src/building/type.h"))}
        source = git("show", f"{revision}:src/building/properties.c")
        entries = re.split(r"(?m)^[ \t]+\[(BUILDING_\w+)\] = \{", source)
        names = [""] * enums["BUILDING_TYPE_MAX"]
        houses = []
        for name, body in zip(entries[1::2], entries[2::2]):
            attr = re.search(r'\.event_data.attr\s*=\s*"([^"]+)"', body)
            if attr:
                names[enums[name]] = name.removeprefix("BUILDING_").lower() if 10 <= enums[name] <= 29 else attr[1].split("|")[0]
            block = re.search(r"\.house_model_data\s*=\s*\{([^}]+)\}", body)
            if block:
                values = {key: int(value) for key, value in re.findall(r"\.(\w+)\s*=\s*(-?\d+)", block[1])}
                assert set(values) == set(HOUSE_FIELDS), name
                houses.append([values[key] for key in HOUSE_FIELDS])
        assert len(houses) in (0, 20)
        snapshots.append((version, names, read_models(revision), houses, revision))
    # A source version can span several releases with different defaults. Keep
    # every candidate; a value matching any of them is not a provable authored edit.
    candidates = {}
    for index, snapshot in enumerate(snapshots):
        version = snapshot[0]
        end = max(version, snapshots[index + 1][0] - 1) if index + 1 < len(snapshots) else 189
        for supported in range(version, end + 1):
            if supported < 175 or supported > 189:
                continue
            candidates.setdefault(supported, []).append(index)
    lines = ["// Generated by tools/generate_augustus_model_defaults.py from Augustus (GPL-3.0).", f"// Target {TARGET}; import baselines only, never runtime definitions.", "#pragma once", "namespace augustus_model_defaults {", "struct Baseline { int version; const char *const *names; const int (*buildings)[6]; int building_count; const int (*houses)[17]; };" ]
    for index, (_, names, buildings, houses, revision) in enumerate(snapshots):
        lines.append(f"// Producer {revision}")
        lines.append(f"inline constexpr const char *names_{index}[] = {{" + ", ".join('"' + name + '"' for name in names) + "};")
        lines.append(f"inline constexpr int buildings_{index}[][6] = {{")
        lines.extend("    {" + ", ".join(map(str, values)) + "}," for values in buildings)
        lines.append("};")
        if houses:
            lines.append(f"inline constexpr int houses_{index}[][17] = {{")
            lines.extend("    {" + ", ".join(map(str, values)) + "}," for values in houses)
            lines.append("};")
    lines.append("inline constexpr Baseline candidates[] = {")
    for version, indices in candidates.items():
        for index in indices:
            houses = f"houses_{index}" if snapshots[index][3] else "nullptr"
            lines.append(f"    {{{version}, names_{index}, buildings_{index}, {len(snapshots[index][2])}, {houses}}},")
    lines.extend(["};", "}", ""])
    (ROOT / "src/game/augustus_model_defaults.generated.h").write_text("\n".join(lines), encoding="utf-8")
    print(f"Generated {len(snapshots)} producer baselines across {len(candidates)} save versions.")


if __name__ == "__main__":
    generate()
