// DO NOT EDIT. This file is generated by the project version step.
#include "game/system.h"

#define AUGUSTUS_VERSION "4.0.0"
#define AUGUSTUS_VERSION_SUFFIX " unknown development version"

const char *system_version(void)
{
    return AUGUSTUS_VERSION AUGUSTUS_VERSION_SUFFIX;
}
